#! /bin/bash
#  Generate the game texture atlas and copy the relevant PNGs

TexturePacker GameAtlas.tps

# cp GameAtlas_Scale1.png GameAtlas_Scale1_png.bytes
# cp GameAtlas_Scale2.png GameAtlas_Scale2_png.bytes
# cp GameAtlas_Scale4.png GameAtlas_Scale4_png.bytes
# mv GameAtlas_Scale1_png.bytes ../SnowUnity/Assets/Resources/Atlases/GameAtlas_Scale1_png.bytes
# mv GameAtlas_Scale2_png.bytes ../SnowUnity/Assets/Resources/Atlases/GameAtlas_Scale2_png.bytes
# mv GameAtlas_Scale4_png.bytes ../SnowUnity/Assets/Resources/Atlases/GameAtlas_Scale4_png.bytes
